Fix spawn fallback
pypa/distutils pull request #89
Opened 2021-12-23 04:18 UTC by isuruf

Note that using unittest.mock doesn't fix the env in the subprocess.

For eg:
```python
import unittest.mock
import os
import subprocess
with unittest.mock.patch('os.environ', {"FOO": "bar"}):
     print(os.environ["FOO"])
     subprocess.check_call("echo FOO=$FOO", shell=True)
```
outputs
```
bar
FOO=
```

2021-12-23 16:39 UTC, jaraco requested changes
What is the issue this change is attempting to fix? Has this code ever worked?

2021-12-23 16:39 UTC, jaraco commented on distutils/_msvccompiler.py
> +        old_path = os.getenv("PATH")
Is PATH the only variable that needs to be patched? Can you implement a contextmanager that has the equivalent simplicity of `unittest.mock.patch`?

2021-12-23 16:41 UTC, jaraco commented on distutils/_msvccompiler.py
> +        old_path = os.getenv("PATH")
I did some searching and found [this article](https://adamj.eu/tech/2020/10/13/how-to-mock-environment-variables-with-pythons-unittest/), which suggests using mock.patch.dict on os.environ will have the intended effect.

2021-12-23 22:42 UTC, isuruf commented
> What is the issue this change is attempting to fix?

`env` variable has changes to `PATH` that is ignored because of the way `mock.patch` worked. This made code depending on `numpy` fail. See the linked issue above.

> Has this code ever worked?

This code worked before https://github.com/pypa/distutils/commit/360aadc4c2a9941a68a3f3f63375ce5380fef6a0, but when the fallback was introduced in 6e92cdabaff71ab2bab3300763101fb8f84c367f, this stopped working.

2021-12-24 00:10 UTC, jaraco commented
Reading through the issue reported in Numpy, the fix for #15 was incomplete (did not have the intended effect), but no one noticed because SETUPTOOLS_USE_DISTUTILS=stdlib became the default again... until earlier this week when the local copy of distutils was reintroduced by default.

2021-12-24 00:14 UTC, isuruf commented
Yep. Another reason is that for this issue to appear you need to have an environment without Visual Studio tools activated which is something done in most CI scripts and the lack of a PATH update doesn't matter.

2021-12-24 00:17 UTC, jaraco commented
Using the example, it seems that patch.dict works as expected:

```
import unittest.mock
import os
import subprocess
with unittest.mock.patch.dict(os.environ, {"FOO": "bar"}):
    print(os.environ["FOO"])
    subprocess.check_call("echo FOO=$FOO", shell=True)
```

outputs

```
bar
FOO=bar
```

2021-12-24 00:20 UTC, jaraco approved these changes

2021-12-24 00:20 UTC, merged

2021-12-24 00:35 UTC, isuruf commented
Thanks